name: CoordLeak
version: '1.0-SNAPSHOT'
main: com.qhuy.coordLeak.CoordLeak
api-version: '1.21'
authors: [ qhuy ]
description: Allows players to buy usages to leak the coordinates of random online players.
depend: [Vault]
softdepend: [Essentials]
permissions:
  coordleak.admin:
    default: op
  coordleak.use:
    default: true
commands:
  buyusage:
    usage: /buyusage
    description: Buy usages for the /coord command.
    permission: coordleak.use
  setusage:
    usage: /setusage <player> <amount>
    description: Set usage count.
    permission: coordleak.admin
  coord:
    usage: /coord
    description: Leak the coordinates of a random online player.
    permission: coordleak.use
  creload:
    usage: /creload
    description: Reload the plugin's configuration.
    permission: coordleak.admin
