name: Maven CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21 ( Temurin )
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Project with Maven
      run: mvn -B clean package

    - name: Upload compiled JAR
      uses: actions/upload-artifact@v4
      with:
        name: NighlyBuild
        path: target/*.jar
        if-no-files-found: error
        compression-level: 0
        overwrite: true
